spring: 
  application:
    name: Consumer-app
  profiles:
    active: dev
    
    
---

spring:
  profiles: dev
  
kafka.broker: localhost:9092,localhost:9093,localhost:9094
enable.auto.commit: true
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: my-topic
